server:
  port: 8081
spring:
  application:
    name: storage-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///seata_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: 112.124.55.2:8848
mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      id-type: auto
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 112.124.55.2:8848
      group: SEATA_GROUP
      namespace: 31684aa2-637e-480e-9960-bb3a310770d6
      cluster: default
      username: nacos
      password: nacos
  tx-service-group: my_test_tx_group # 事务组名称
  data-source-proxy-mode: AT
  config:
    type: nacos
    nacos:
      server-addr: 112.124.55.2:8848
      namespace: 31684aa2-637e-480e-9960-bb3a310770d6
      group: SEATA_GROUP
      username: nacos
      password: nacos
      data-id: seataServer.properties
      context-path: